var subjectSelect = document.querySelector("#subject");
var nameInput = document.querySelector("#name");
var gradeInput = document.querySelector("#grade");
var addButton = document.querySelector("#addButton");
var numOfPassed = document.querySelector('#numOfPassed');
var numOfFailed = document.querySelector('#numOfFailed');
var percentOfPassed = document.querySelector('#percentOfPassed');
var percentOfFailed = document.querySelector('#percentOfFailed');
var passedList = document.querySelector('#passedList');
var failedList = document.querySelector('#failedList');
var totalStudents = document.querySelector('#totalStudents');
var passedLis = document.querySelectorAll('.passedLi')
var nameAndSurname;
var selectedSubject;
var gradeSelected;
var newStudent;
var newSubject;
var name;
var surname;
var nameAndSurnameArray;
var numOfFailedNumber = 0; 
var numOfPassedNumber = 0; 
var totalNumOFStudents = 0;
var percentOfFailedNum = 0;
var percentOfPassedNum = 0;
var passedLi;
var failedLi;
var passedGrade;
var failedGrade;
var passedGradeInput;
var failedGradeInput;
var xSpanPassed;
var xSpanPassedInput;
var xSpanFailed;
var xSpanFailedInput;

